export const items = [
  {
    id: 1,
    color: "from-red-300 to-blue-300",
    title: "Turnos Web App",
    desc: "Aplicación web que permite la reserva de turnos para empresas con sucursales físicas, posibilitando la administración de la cantidad de clientes en la locación. Cada sucursal podrá diferenciar la cantidad de clientes en simultáneo que podrá recibir y los rangos horarios, desde el usuario administrador/operador. Cada turno será de 15 minutos, y se pueden cancelar hasta con 2 horas de antelación.",
    img: "/projects/project1.jpg",
    links: [
      { title: "Github", path: "https://github.com/juan-ma526/App-Turnos-Redux/tree/main/turnos-app" },
      { title: "Video", path: "https://www.youtube.com/watch?v=wwARGlKkVmY" },
    ],
    icons: [
      "/icons/html.png",
      "/icons/react.png",
      "/icons/redux.png",
      "/icons/express.png",
      "/icons/mongoDB.png",
      "/icons/jwt.png",
      "/icons/sass.png",
      "/icons/javascript.png",
    ],
  },
  {
    id: 2,
    color: "from-blue-300 to-violet-300",
    title: "TMBD Movie Database",
    desc: "Aplicación de Películas, para poder ver las películas o series en cartelera o por género, y poder ver información de cada película o serie para poder ver el tráiler de cada una. A su vez podes tener un registro de usuario para poder almacenar las películas favoritas y tener una lista de películas o series favoritas.",
    img: "/projects/project2.jpg",
    links: [
      { title: "Github", path: "https://github.com/juan-ma526/TMDB-V2" },
      { title: "Video", path: "https://www.youtube.com/watch?v=NE1TvG3aA6A" },
      { title: "Demo", path: "https://tmdb-v2-two.vercel.app/" },
    ],
    icons: [
      "/icons/html.png",
      "/icons/react.png",
      "/icons/express.png",
      "/icons/postgresql.png",
      "/icons/jwt.png",
      "/icons/css.png",
      "/icons/javascript.png",
    ],
  },
  {
    id: 3,
    color: "from-violet-300 to-purple-300",
    title: "Ecommerce COMO EN CASA",
    desc: "Aplicación Ecommerce para visualizar y poder ordenar entre platos de comidas, con la posibilidad de tener administradores para manejar los productos y el stock de cada comida, y poder manipular las órdenes. También tiene un carrito de compras en el que queda un historial de los pedidos realizados.",
    img: "/projects/project3.jpg",
    links: [{ title: "Github", path: "https://github.com/juan-ma526/Ecommerce-Como-en-Casa" }],
    icons: [
      "/icons/html.png",
      "/icons/react.png",
      "/icons/redux.png",
      "/icons/express.png",
      "/icons/postgresql.png",
      "/icons/jwt.png",
      "/icons/css.png",
      "/icons/javascript.png",
    ],
  },
  {
    id: 4,
    color: "from-purple-300 to-red-300",
    title: "Mini Pago app MercadoPago",
    desc: "Aplicación sencilla para implementar el uso de mercadoPago en una compra.",
    img: "/projects/project4.jpg",
    links: [
      { title: "Github", path: "https://github.com/juan-ma526/mercadoPago" },
      { title: "Video", path: "https://www.youtube.com/watch?v=oEZyWe-fdeY" },
    ],
    icons: ["/icons/html.png", "/icons/express.png", "/icons/css.png", "/icons/javascript.png"],
  },
  {
    id: 5,
    color: "from-purple-300 to-red-300",
    title: "Sorteo Devtalles, con Discord",
    desc: "Aplicación web para el concurso realizado para la página https://cursos.devtalles.com/. Dicha app fue realizada en una semana con la posibilidad de crear sorteos, modificarlos y eliminarlos. La participación es realizada con discord api, se necesita estar en el servidor de devtalles para poder participar, manejando las rutas con esas condiciones. También se tiene la posibilidad de elegir un ganador y ver los participantes en cada sorteo, con la posibilidad de eliminar alguno de ellos.",
    img: "/projects/project5.jpg",
    links: [
      { title: "Github", path: "https://github.com/juan-ma526/devtalles-codequest-sorteos" },
      { title: "Video", path: "https://www.youtube.com/watch?v=Pqops93TiPI" },
      { title: "Demo", path: "https://devtalles-codequest-sorteos-gamma.vercel.app/" },
    ],
    icons: [
      "/icons/html.png",
      "/icons/nextjs.png",
      "/icons/express.png",
      "/icons/mongoDB.png",
      "/icons/jwt.png",
      "/icons/tailwind.png",
      "/icons/javascript.png",
    ],
  },
  {
    id: 6,
    color: "from-purple-300 to-red-300",
    title: "Sorteo Rifa",
    desc: "Mini Proyecto Freelance. Se trata de una aplicación web para la compra de rifas, para sortear determinados productos. Con la posibilidad de comprar n cantidad de tickets, dándote la cantidad de tickets comprados. El admin puede crear el stock de tickets, borrar dicho stock, seleccionar un ganador, buscar un ticket en específico, y ver los tickets que fueron comprados.",
    img: "/projects/project6.jpg",
    links: [
      { title: "Github", path: "https://github.com/juan-ma526/sorteo-rifa" },
      { title: "Video", path: "https://www.youtube.com/watch?v=WDKeG76QRxU&t=2s" },
    ],
    icons: [
      "/icons/html.png",
      "/icons/react.png",
      "/icons/express.png",
      "/icons/mongoDB.png",
      "/icons/css.png",
      "/icons/javascript.png",
    ],
  },
  {
    id: 7,
    color: "from-purple-300 to-red-300",
    title: "Perfect Mentor App",
    desc: "Aplicación web (Mobile first) que permita encontrar a tu mentor ideal. Permite la creación de usuarios y la posibilidad de elegir entre ser un mentor o un mentee, poder machear entre los usuarios verificados disponibles, y con los match positivos tener un chat para comunicarse con ellos.",
    img: "/projects/project7.jpg",
    links: [{ title: "Github", path: "https://github.com/juan-ma526/perfectMentor" }],
    icons: [
      "/icons/html.png",
      "/icons/nextjs.png",
      "/icons/express.png",
      "/icons/mongoDB.png",
      "/icons/jwt.png",
      "/icons/tailwind.png",
      "/icons/typescript.png",
      "/icons/javascript.png",
    ],
  },
];

export const skills = [
  "JAVASCRIPT",
  "REACT",
  "REDUX",
  "NEXTJS 14",
  "CSS",
  "SASS",
  "TAILWIND CSS",
  "NODE JS",
  "MONGODB",
  "POSTGRESQL",
  "JWT",
  "AUTH JS",
  "EXPRESS JS",
  "TYPESCRIPT",
];

("#ff8408");
